In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [3]:
data.describe()

price         size         year
count     100.000000   100.000000   100.000000
mean   292289.470160   853.024200  2012.600000
std     77051.727525   297.941951     4.729021
min    154282.128000   479.750000  2006.000000
25%    234280.148000   643.330000  2009.000000
50%    280590.716000   696.405000  2015.000000
75%    335723.696000  1029.322500  2018.000000
max    500681.128000  1842.510000  2018.000000

In [38]:
x = data[['size', 'year']]
y = data['price']

In [39]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [40]:
reg.intercept_

-5772267.017463281

In [41]:
reg.score(x,y)

0.7764803683276791

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [42]:
r2 = reg.score(x,y)
n = x.shape[0] #sample
p = x.shape[1]
r_adj = 1 - (1- r2)*(n-1)/(n-p-1)

In [43]:
r_adj

0.7718717161282498

In [50]:
reg.predict([[750, 2009]])

C:\Users\Salih\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([258330.34465995])

In [51]:
from sklearn.feature_selection import f_regression 

In [52]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [54]:
p_values = f_regression(x,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [55]:
p_values.round(3)

array([0.   , 0.357])

In [56]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
reg_summary['Coefficients'] = reg.coef_

In [57]:
reg_summary['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357

It seems that 'Year' is not event significant, therefore we should remove it from the model.